### ISSUE TITLE
skippy stops after 2 runs on ubuntu

### ISSUE THREAD

**Issue by TJNK** [AlbertBrand/skippyjs#5]
Skippy stops tracking changes/ wachting after the runner did 2 turns on ubuntu (15.04)

**Comment by AlbertBrand** [comment]
It does work properly on Mac. Maybe the problem is in the 'chokidar' file watcher dependency.

**Comment by AlbertBrand** [comment]
Solved with workaround mentioned in Chokidar issue, see release 0.1.8
